#!/usr/bin/env bash

DIR_NAME=$(dirname $(readlink -f ${0}))
BASE=$(dirname $(readlink -f "${DIR_NAME}/../.."))
DOMAIN=$(basename $(readlink -f "${DIR_NAME}/.."))
APP="${BASE}/app/${DOMAIN}"
BRANCH="master"

while read oldrev newrev ref
do
    BRANCH=`echo ${ref} | cut -d/ -f3`
done

cd ${APP}

if [ "$(docker ps -q -f name=${DOMAIN}-app)" ]; then
  docker-compose stop
fi

cd $(dirname ${DIR_NAME})

GIT_WORK_TREE="${APP}" git checkout -f ${BRANCH}

cd ${APP}

# chown -R heimdall:heimdall .

if [ -f ".scripts/setup.sh" ]; then
  sh .scripts/setup.sh
fi

if [ -f "docker-compose.yml" ]; then
#  docker-compose rm -v -f
  docker-compose down --remove-orphans
  docker-compose up -d
fi

if [ -f ".scripts/install.sh" ]; then
  sh .scripts/install.sh
fi
